services:
  dev-env:
    build:
      context: .
      dockerfile: Dockerfile.dev
      args:
        USERNAME: ${USERNAME}
        UID: ${D_UID}
        GID: ${D_GID}
        GIT_USER: ${GIT_USER}
        GIT_EMAIL: ${GIT_EMAIL}
        JAVA_VERSION: ${JAVA_VERSION}
        NODE_VERSION: ${NODE_VERSION}

    restart: always
    volumes:
      - ./:/home/${USERNAME}/app
      - ~/.ssh:/home/${USERNAME}/.ssh

    user: ${D_UID}:${D_GID}

    tty: true
    network_mode: host

  postgres:
    image: postgres:${POSTGRES_VERSION}

    restart: always
    ports:
      - 5432:5432
    volumes:
      - .data:/var/lib/postgres/data

    environment:
      POSTGRES_PASSWORD: dev

